#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = $app->make(Illuminate\Console\Input\ArgvInput::class),
    $output = $app->make(Illuminate\Console\Output\ConsoleOutput::class)
);

$kernel->terminate($input, $status);

exit($status);
